### ISSUE TITLE
TypeError in plot_

### ISSUE THREAD

**Issue by QtRoS** [Atcold/pytorch-Deep-Learning-Minicourse#11]
I've got the following error:

> TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

in `04-spiral_classification.ipynb` in this line:

> plot_model(X, y, model)

Seems that only `X` is moved to CPU via `X = X.cpu()`, but not `y`. As workaround it can be fixed like this:

`plot_model(X, y.cpu(), model)`

**Comment by Atcold** [comment]
Can you submit a PR with this fix?
