### ISSUE TITLE
CSS table style sucks

### ISSUE THREAD

**Issue by Atcold** [Atcold/pytorch-Deep-Learning-Minicourse#28]
This is what a table currently looks like (light background for first row).

![Screenshot 2020-02-03 15 00 45](https://user-images.githubusercontent.com/2119355/73686465-05871900-4696-11ea-9ad9-b9de7c08af86.png)

**Comment by ebetica** [comment]
I think it thinks the first row is a header, are you using this syntax? https://kramdown.gettalong.org/quickref.html#tables

**Comment by ebetica** [comment]
For reference - the table CSS with big tables should look like: https://doc.rust-lang.org/book/appendix-02-operators.html

**Comment by Atcold** [comment]
Okay, I'll kill the table header then.
Thanks.

**Comment by Atcold** [comment]
Hmm... On my local version killing the headers works.
On the public one, it does not. Maybe it's caching?
